# Set to true to add reviewers to pull requests
addReviewers: true

# Set to 'author' to add PR 작성자를 담당자로 할당 (원하면 false도 가능)
addAssignees: author

# GitHub 사용자명 리스트
reviewers: 
  - 7SH7 
  - bsoyn
  - dahxxn
  - doyooon
  - haeyekim
  - leewonwook
  - TaeHyunaivle 

# 무작위로 선택할 리뷰어 수
numberOfReviewers: 1

# PR 담당자로 등록할 인원 수
numberOfAssignees: 1

# PR 제목에 아래 키워드가 포함되면 reviewer 자동 지정 생략
skipKeywords:
  - wip
