apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-fast-${SERVICE_NAME}-hpa
  namespace: smart-fast-${SERVICE_NAME}
  labels:
    app: smart-fast-${SERVICE_NAME}
    service: ${SERVICE_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-fast-${SERVICE_NAME}
  minReplicas: 1
  maxReplicas: 5

  # 스케일링 정책
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60   # 1분 안정화
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60

  metrics:
    # CPU 기반 스케일링
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    # 메모리 기반 스케일링
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80