apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sf-${SERVICE_NAME}-hpa
  namespace: sf-${SERVICE_NAME}
  labels:
    app: sf-${SERVICE_NAME}
    service: ${SERVICE_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sf-${SERVICE_NAME}
  minReplicas: 1
  maxReplicas: 2  # 5 → 2 (개발환경에서는 최대 2개)

  # 보수적 스케일링 정책 (메모리 부족 방지)
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 300 → 600 (10분 안정화)
      policies:
        - type: Percent
          value: 50
          periodSeconds: 120  # 60 → 120 (더 천천히)
    scaleUp:
      stabilizationWindowSeconds: 300   # 60 → 300 (5분 안정화)
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300  # 60 → 300 (더 천천히)

  metrics:
    # 메모리 기반 스케일링만 (실제 병목)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90  # 80 → 90 (더 보수적, 실제 사용량 고려)

    # CPU 스케일링 제거 (불필요하고 혼란 야기)
    # - type: Resource
    #   resource:
    #     name: cpu
    #     target:
    #       type: Utilization
    #       averageUtilization: 70