apiVersion: v1
kind: Service
metadata:
  name: smart-fast-${SERVICE_NAME}-service
  namespace: smart-fast-${SERVICE_NAME}
  labels:
    app: smart-fast-${SERVICE_NAME}
    service: ${SERVICE_NAME}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: smart-fast-${SERVICE_NAME}