model:
  name: random_forest
  # Hugging Face Hub 리포지토리와 파일명으로 경로를 변경합니다.
  # "HuggingFace_Repo_ID::파일명" 형식으로 표기하면 더 명확합니다.
  model_repo_id: "23smartfactory/Ecoating_model"
  model_filename: "Ecoating_model.pkl"

training:
  random_state: 42
  test_size: 0.2
  n_estimators: 300
  max_depth: 20
  max_features: sqrt
  min_samples_split: 2

threshold:
  shap_threshold: 2.0
  thickness_error_threshold: 0.1

features:
  input_columns:
    - PT_jo_V_1
    - PT_jo_A_Main_1
    - PT_jo_TP
  target_column: Thick

logs:
  log_issue_codes:
    voltage_invalid: "PAINT-EQ-VOL-INVALID"
    current_invalid: "PAINT-EQ-CUR-INVALID"
    temperature_invalid: "PAINT-EQ-TEM-INVALID"
    machine_issue: "PAINT-EQ-MCH"
    voltage_issue: "PAINT-EQ-VOL"
    current_issue: "PAINT-EQ-CUR"
    temperature_issue: "PAINT-EQ-TEM"
  # 로그 파일 저장 경로 수정 (선택 사항, 현재 경로 유지)
  file_path: "logs/issue_logs.jsonl" # 이 경로는 서비스 루트 기준
  # 입력 컬럼명과 이슈 코드 사이의 매핑을 명시적으로 정의
  issue_map:
    PT_jo_V_1: "PAINT-EQ-VOL"
    PT_jo_A_Main_1: "PAINT-EQ-CUR"
    PT_jo_TP: "PAINT-EQ-TEM"

validation:
  voltage_range: [20, 350]
  current_range: [5, 400]
  temperature_range: [25, 40]

file_upload:
  column_mapping:
    machineId: "machineId"
    timeStamp: "timeStamp"
    Thick: "thick"
    PT_jo_V_1: "voltage"
    PT_jo_A_Main_1: "current"
    PT_jo_TP: "temper"